### ISSUE TITLE
Bug- The view menu button should take the user to the Menu page.

### ISSUE THREAD

**Issue by samruddhikurhe** [khushi-joshi-05/Food-ordering-website#87] opened 2024-05-10 17:37 UTC
Please assign me this issue under GSSOC24, to fix the bug that after clicking on 'View all menu' button the user should be taken to the Menu page of the website. 
![Screenshot 2024-05-10 230654](https://github.com/khushi-joshi-05/Food-ordering-website/assets/132932618/ecc05b56-bb2d-436a-a183-bf0b45f3ec0c)

**Comment by Pratyaksh0910** [comment] 2024-05-10 18:05
Hey there! I'm Pratyaksh Agrawal, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC.
You can find me on LinkedIn : https://www.linkedin.com/in/pratyaksh-agrawal-2aa032220/
Looking forward to contributing to GSSOC 2024!

**Comment by Priyanka-Ray-Choudhury** [comment] 2024-05-10 22:27
Hi @khushi-joshi-05, I'd like to tackle the assignment regarding the bug where the "View Menu" button isn't directing users to the Menu page as intended. Could you please assign this task to me with the GSSOC tag? Thanks!

**Comment by samruddhikurhe** [comment] 2024-05-11 06:09
Hello @khushi-joshi-05, I am full stack developer and I have identified this issue. Please assign me this issue under GSSOC24.(on first come first chance basis).

**Comment by Shivangbarnwal** [comment] 2024-05-11 06:15
Hi @khushi-joshi-05, I can fix this issue. Also moving from one page to next always opens up in a new tab which creates a mess, I can fix that too. Could you please assign this task to me under GSSOC 24?  Thanks!!

**Comment by sunny0625** [comment] 2024-06-23 11:50
This issue is already solved.
Try to contribute to different issues.

**Closed by sunny0625** 2024-06-23 11:50 UTC
