### ISSUE TITLE
Footer social media links and play store links aren't working

### ISSUE THREAD

**Issue by AlaynaShaheen** [khushi-joshi-05/Food-ordering-website#19] opened 2024-05-09 13:50 UTC
Hello Khushi,

I am a contributor in GSSoC'24. I found this issue and I can solve this by adding social media links to the footer. I can improve the UI by adding logos of google play store and app store instead of text buttons which helps in better user navigation. Please assign this to me under GSSoC'24.

Regards,
Alayna Shaheen

**Comment by 07sumit1002** [comment] 2024-05-09 16:04
Hello Khushi,

I'm Sumit Kumar, a contributor participating in GSSOC'24. I'm interested in contributing to this particular issue. It seems like it can be resolved by using the href attribute in the already utilized anchor tag. I'm eager to tackle this challenge and contribute to the project. Looking forward to your guidance on how to proceed.

Regards,
Sumit Kumar

**Comment by harshmishra19** [comment] 2024-05-09 18:52
Hello @khushi-joshi-05 Can you plz assign this issue to me under GSSOC'24

**Comment by rishyym0927** [comment] 2024-05-10 08:10
Hi,
I want to work on this issue

**Comment by paridhi1509** [comment] 2024-05-10 15:02
I would like to work on this issue
Please assign it to me
Thank you

**Comment by royalrajputayush** [comment] 2024-05-11 08:05
I want to work on this issue, please assign me this under GSSoC level 2.

**Comment by satyendushukla** [comment] 2024-05-11 16:52
hey,,i am able to complete this task.

**Comment by bhuvangoel04** [comment] 2024-05-11 17:23
Hi @khushi-joshi-05 , Can you please assign me this issue under GSSOC'24. Also please add the level label to it.

**Comment by DhruvPandey1** [comment] 2024-05-12 07:46
I had resolved this issue please see my PR

**Comment by sunny0625** [comment] 2024-05-12 16:14
@khushi-joshi-05
If the issue is solved please close the issue!

**Closed** 2024-05-13 15:26 UTC
Labels: duplicate, gssoc
